// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/tuannm-sns/auth-svc/api"
	"github.com/tuannm-sns/auth-svc/internal/repository/pg"
	"github.com/tuannm-sns/auth-svc/internal/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// db connection will be injected by hand
func InitializeUserController(conn *gorm.DB) api.UserController {
	userRepository := pg.NewPgUserRepository(conn)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userController := api.NewUserController(userUsecase)
	return userController
}
